### ISSUE TITLE
Question: Compilation issues with a lot of Pods

### ISSUE THREAD

**Issue by TadeasKriz** [leavez/cocoapods-static-swift-framework#1]
First of all, this is a great plugin and I'm looking forward to using it in all of our projects. Thank you for this!

Unfortunately I'm facing a lot of issues with existing Pods. I'm not exactly sure how did it work before, but there were some frameworks that didn't need `import X` in the source files of Pods (mainly **UIKit** and **Foundation**).

So now there are many Pods that don't compile with this plugin active, because they lack those imports in their source files.

My question is, can we workaround it somehow?

Thanks!

**Comment by leavez** [comment]
Static framework support on cocoapods 1.4 is totally a disaster. Cocoapods 1.5 beta is released now, and everything works fine.
