### ISSUE TITLE
Does it support cocoapods v1.9.3?

### ISSUE THREAD

**Issue by brave723** [leavez/cocoapods-static-swift-framework#11]
no work

this is my podfile 

plugin 'cocoapods-static-swift-framework'

use_frameworks!
all_binary!

platform :ios, '10.0'

target 'CocoapodsBinaryKit_Example' do
  pod 'CocoapodsBinaryKit', :path => '../'

  pod 'IQKeyboardManagerSwift',  :binary => true
  pod 'Alamofire' ,  :binary => true

end

**Comment by buptwsg** [comment]
It seems that this plugin does not support binary.
