### ISSUE TITLE
Using the plugin to create a framework

### ISSUE THREAD

**Issue by sirghi** [leavez/cocoapods-static-swift-framework#2]
Hi, sorry for opening an issue, but this was the only way I could find to get in touch

I'm trying to develop a framework, written in swift, that will be distributed as binary, and that depends on other frameworks. The goal is to combine all of them into one unit. Tried loads of methods out there. Your plugin was my last stop. The framework is built ok. But when trying to use it in app projects, I get a compile error around modules. Namely that it can't find the dependencies module, even though expectation was for it to be incorporated as a black box.

Have you any experience in building such frameworks?
Cheers

**Comment by leavez** [comment]
This plugin is not built for this.

Yes, you should use static library in this case. But it’s for the library of your library. The right to do : 

1 create new project and add a framework target (no app target). 

2 add Podfile to this project. In Podfile, add your dependencies and don’t use “use_framework!” . (So the libs are linked statically.

3 built, and the product of the project is what you want

**Comment by sirghi** [comment]
@leavez That's what I did, and having the error above. If you are able to double check that it works on your side, including cleaning all the build cache because there's a false positive that it picks up the dependency from the cache, would be grateful.
